{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "",
  "CTAs": [],
  "faultNumber": "40789564",
  "multipleFaultNumbers": null,
  "date": "2020-12-07T11:59:30",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2020-12-07T11:59:30",
  "information": "",
  "actualTimeOfRestoration": "2020-12-07T11:59:30",
  "outageCentrePoint": {
    "lat": 53.843236,
    "lng": -2.973815
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 8JL, FY6 8JS, FY6 8JT, FY6 8JU, FY6 8JY, FY6 8TU",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "TRAN"
}