{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "40783888",
  "multipleFaultNumbers": null,
  "date": "2020-10-30T03:32:00",
  "region": "Colne",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2020-10-30T03:32:00",
  "information": "",
  "actualTimeOfRestoration": "2020-10-30T03:32:00",
  "outageCentrePoint": {
    "lat": 53.856924,
    "lng": -2.161295
  },
  "outageLocations": null,
  "AffectedPostcodes": " BB8 0HS, BB8 0JE, BB8 0JJ, BB8 0JL, BB8 0LL, BB8 9HT, BB8 9HX, BB8 9HY",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}