{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "40783301",
  "multipleFaultNumbers": null,
  "date": "2020-10-29T15:48:50",
  "region": "Colne",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2020-10-29T15:48:50",
  "information": "",
  "actualTimeOfRestoration": "2020-10-29T15:48:50",
  "outageCentrePoint": {
    "lat": 53.878086,
    "lng": -2.174472
  },
  "outageLocations": null,
  "AffectedPostcodes": " BB8 1VV, BB8 7GQ, BB8 7LB, BB8 7LD, BB8 7LF, BB8 7LG, BB8 7LN, BB8 7NB",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}