{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "40790499",
  "multipleFaultNumbers": null,
  "date": "2020-12-15T15:15:51",
  "region": "Colne",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2020-12-15T15:15:51",
  "information": "",
  "actualTimeOfRestoration": "2020-12-15T15:15:51",
  "outageCentrePoint": {
    "lat": 53.861953,
    "lng": -2.168359
  },
  "outageLocations": null,
  "AffectedPostcodes": " BB8 9DX, BB8 9DY, BB8 9DZ, BB8 9ER",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GS"
}