{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "UpdateInfo": null,
  "CTAs": [],
  "faultNumber": "40811132",
  "multipleFaultNumbers": null,
  "date": "2021-04-23T23:27:38",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": null,
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-04-23T23:27:38",
  "information": "",
  "actualTimeOfRestoration": "2021-04-23T23:27:38",
  "outageCentrePoint": {
    "lat": 53.847348,
    "lng": -2.996775
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 7BX, FY6 7RY, FY6 7RZ, FY6 7SA, FY6 7SB, FY6 7SD, FY6 7SE, FY6 7SF, FY6 7ST, FY6 7SZ, FY6 7UR, FY6 7WJ",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GS"
}