{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "UpdateInfo": null,
  "CTAs": [],
  "faultNumber": "40815882",
  "multipleFaultNumbers": null,
  "date": "2021-05-30T06:34:56",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-05-30T06:34:56",
  "information": "",
  "actualTimeOfRestoration": "2021-05-30T06:34:56",
  "outageCentrePoint": {
    "lat": 53.847527,
    "lng": -3.016843
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 7PZ, FY6 7QN, FY6 7QP, FY6 7QR, FY6 7QU, FY6 7QW",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}