{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "UpdateInfo": null,
  "CTAs": [],
  "faultNumber": "60509399",
  "multipleFaultNumbers": null,
  "date": "2021-04-27T15:24:34",
  "region": "Dalton-In-Furness",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": null,
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-04-27T15:24:34",
  "information": "",
  "actualTimeOfRestoration": "2021-04-27T15:24:34",
  "outageCentrePoint": {
    "lat": 54.147111,
    "lng": -3.182267
  },
  "outageLocations": null,
  "AffectedPostcodes": " LA15 8PE, LA15 8PF, LA15 8XA, LA15 8XB, LA15 8XD, LA15 8XG",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}