{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "60504881",
  "multipleFaultNumbers": null,
  "date": "2021-02-25T18:37:08",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-02-25T18:37:08",
  "information": "",
  "actualTimeOfRestoration": "2021-02-25T18:37:08",
  "outageCentrePoint": {
    "lat": 53.92779,
    "lng": -2.991711
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 0BL",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}