{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "UpdateInfo": null,
  "CTAs": [],
  "faultNumber": "60508563",
  "multipleFaultNumbers": null,
  "date": "2021-04-19T16:45:27",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-04-19T16:45:27",
  "information": "",
  "actualTimeOfRestoration": "2021-04-19T16:45:27",
  "outageCentrePoint": {
    "lat": 53.928016,
    "lng": -2.991721
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 0AD, FY6 0BH, FY6 0BL, FY6 0BQ, FY6 0BT",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}