{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "UpdateInfo": null,
  "CTAs": [],
  "faultNumber": "60508523",
  "multipleFaultNumbers": null,
  "date": "2021-04-16T19:11:44",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-04-16T19:11:44",
  "information": "",
  "actualTimeOfRestoration": "2021-04-16T19:11:44",
  "outageCentrePoint": {
    "lat": 53.928634,
    "lng": -2.978769
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 0DW, FY6 0JY, FY6 0ND, FY6 0NE, FY6 0NF",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}