{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "60501237",
  "multipleFaultNumbers": null,
  "date": "2021-01-19T00:38:54",
  "region": "Dalton-In-Furness",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-01-19T00:38:54",
  "information": "",
  "actualTimeOfRestoration": "2021-01-19T00:38:54",
  "outageCentrePoint": {
    "lat": 54.1586,
    "lng": -3.17957
  },
  "outageLocations": null,
  "AffectedPostcodes": " LA15 8RU, LA15 8RX, LA15 8RY",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GS"
}