{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "60501816",
  "multipleFaultNumbers": null,
  "date": "2021-01-25T13:00:58",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 15,
  "estimatedTimeOfRestoration": "2021-01-26T13:00:00",
  "estimatedTimeOfRestorationMajority": "2021-01-25T13:00:58",
  "information": "",
  "actualTimeOfRestoration": "2021-01-25T13:00:58",
  "outageCentrePoint": {
    "lat": 53.928865,
    "lng": -2.972914
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 0EU, FY6 0EX, FY6 0EY, FY6 0EZ, FY6 0FA, FY6 0FB, FY6 0FD, FY6 0HA, FY6 0HB, FY6 0JX, FY6 0PS, FY6 0PX, FY6 0RL",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}