{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "UpdateInfo": null,
  "CTAs": [],
  "faultNumber": "60511272",
  "multipleFaultNumbers": null,
  "date": "2021-05-28T23:33:32",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-05-28T23:33:32",
  "information": "",
  "actualTimeOfRestoration": "2021-05-28T23:33:32",
  "outageCentrePoint": {
    "lat": 53.875544,
    "lng": -2.961422
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 9AH, FY6 9EB, FY6 9ED, FY6 9EH, FY6 9EP",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GS"
}