{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "UpdateInfo": null,
  "CTAs": [],
  "faultNumber": "60511780",
  "multipleFaultNumbers": null,
  "date": "2021-06-04T14:33:30",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 1,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-06-04T14:33:30",
  "information": "",
  "actualTimeOfRestoration": "2021-06-04T14:33:30",
  "outageCentrePoint": {
    "lat": 53.931035,
    "lng": -2.969612
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 0HB, FY6 0HE, FY6 0HG",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GS"
}