{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "UpdateInfo": null,
  "CTAs": [],
  "faultNumber": "60513575",
  "multipleFaultNumbers": null,
  "date": "2021-07-02T17:40:44",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-07-02T17:40:44",
  "information": "",
  "actualTimeOfRestoration": "2021-07-02T17:40:44",
  "outageCentrePoint": {
    "lat": 53.921796,
    "lng": -2.965667
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 0EJ, FY6 0HN, FY6 0NT, FY6 0NU",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}